# Generated by Django 3.0.5 on 2020-04-25 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedTestUnit',
            fields=[
                ('test_id', models.CharField(help_text='Unique identifier for test', max_length=32)),
                ('file_size_mb', models.FloatField(help_text='Size of data for speed testing in megabytes')),
                ('unit_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('begin_timestamp', models.DateTimeField(help_text='Timestamp of test beginning')),
                ('file', models.BinaryField(help_text='Binary data for speed testing')),
                ('packet_count', models.IntegerField(help_text='Number of packets in test')),
                ('packet_number', models.IntegerField(help_text='Order number of packet in test')),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpeedTestResult',
            fields=[
                ('test_id', models.CharField(help_text='Unique identifier for test', max_length=32)),
                ('file_size_mb', models.FloatField(help_text='Size of data for speed testing in megabytes')),
                ('result_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('duration', models.DurationField(help_text='Time between current timestamp and timestamp of test beginning')),
                ('speed', models.FloatField(help_text='Speed of connection for current test unit in mbit/sec')),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='connection_speed_measurement.SpeedTestUnit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
