# Generated by Django 3.0.5 on 2020-05-10 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedTest',
            fields=[
                ('test_id', models.AutoField(help_text='Unique identifier for test', primary_key=True, serialize=False, verbose_name='Test ID')),
                ('file_size_mb', models.IntegerField(help_text='Size of data for speed testing in megabytes', verbose_name='File size')),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Tester`s username')),
            ],
        ),
        migrations.CreateModel(
            name='SpeedTestUnit',
            fields=[
                ('unit_id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Unit ID')),
                ('file', models.TextField(blank=True, help_text='Data for speed testing', verbose_name='File data')),
                ('begin_timestamp', models.DateTimeField(help_text='Timestamp of test beginning', verbose_name='Begin')),
                ('packet_count', models.IntegerField(help_text='Number of packets in test', verbose_name='Packet count')),
                ('packet_number', models.IntegerField(help_text='Order number of packet in test', verbose_name='Packet number')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='connection_speed_measurement.SpeedTest', verbose_name='Test ID')),
            ],
        ),
        migrations.CreateModel(
            name='SpeedTestResult',
            fields=[
                ('result_id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Result ID')),
                ('duration', models.DurationField(help_text='Time between current timestamp and timestamp of test beginning', verbose_name='Duration')),
                ('speed', models.FloatField(help_text='Speed of connection for current test unit in mbit/sec', verbose_name='Speed')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='connection_speed_measurement.SpeedTestUnit', verbose_name='Unit ID')),
            ],
        ),
    ]
