# Generated by Django 3.0.5 on 2020-05-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_speed_measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedtestresult',
            name='result_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='speedtestunit',
            name='unit_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
