# Generated by Django 3.0.5 on 2020-05-10 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connection_speed_measurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedTestTotalResult',
            fields=[
                ('total_result_id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Result ID')),
                ('download_speed', models.FloatField(help_text='Speed of connection for current test unit in mbit/sec', verbose_name='Speed')),
                ('upload_speed', models.FloatField(help_text='Speed of connection for current test unit in mbit/sec', verbose_name='Speed')),
                ('server_name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(verbose_name='')),
                ('expiration_date', models.DateTimeField(verbose_name='')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='connection_speed_measurement.SpeedTest', verbose_name='Test ID')),
            ],
        ),
    ]
