# Generated by Django 3.0.5 on 2020-04-25 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connection_speed_measurement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speedtestresult',
            name='file_size_mb',
        ),
        migrations.RemoveField(
            model_name='speedtestresult',
            name='test_id',
        ),
        migrations.RemoveField(
            model_name='speedtestresult',
            name='tester',
        ),
        migrations.RemoveField(
            model_name='speedtestunit',
            name='file',
        ),
        migrations.RemoveField(
            model_name='speedtestunit',
            name='file_size_mb',
        ),
        migrations.RemoveField(
            model_name='speedtestunit',
            name='tester',
        ),
        migrations.CreateModel(
            name='SpeedTest',
            fields=[
                ('test_id', models.CharField(help_text='Unique identifier for test', max_length=32, primary_key=True, serialize=False)),
                ('file', models.BinaryField(help_text='Binary data for speed testing')),
                ('file_size_mb', models.FloatField(help_text='Size of data for speed testing in megabytes')),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='speedtestunit',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='connection_speed_measurement.SpeedTest'),
        ),
    ]
