# Generated by Django 3.0.5 on 2020-05-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_speed_measurement', '0002_speedtesttotalresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedtesttotalresult',
            name='date',
            field=models.DateTimeField(verbose_name='Speed test date'),
        ),
        migrations.AlterField(
            model_name='speedtesttotalresult',
            name='download_speed',
            field=models.FloatField(help_text='Speed of connection for current test unit in mbit/sec', verbose_name='Download average speed'),
        ),
        migrations.AlterField(
            model_name='speedtesttotalresult',
            name='expiration_date',
            field=models.DateTimeField(verbose_name='Expiration access date'),
        ),
        migrations.AlterField(
            model_name='speedtesttotalresult',
            name='server_name',
            field=models.CharField(max_length=50, verbose_name='Server location'),
        ),
        migrations.AlterField(
            model_name='speedtesttotalresult',
            name='upload_speed',
            field=models.FloatField(help_text='Speed of connection for current test unit in mbit/sec', verbose_name='Upload average speed'),
        ),
    ]
