# Generated by Django 3.0.5 on 2020-05-03 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connection_speed_measurement', '0002_auto_20200502_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedtest',
            name='file',
            field=models.BinaryField(help_text='Binary data for speed testing', verbose_name='File data'),
        ),
        migrations.AlterField(
            model_name='speedtest',
            name='file_size_mb',
            field=models.FloatField(help_text='Size of data for speed testing in megabytes', verbose_name='File size'),
        ),
        migrations.AlterField(
            model_name='speedtest',
            name='test_id',
            field=models.AutoField(help_text='Unique identifier for test', primary_key=True, serialize=False, verbose_name='Test ID'),
        ),
        migrations.AlterField(
            model_name='speedtest',
            name='tester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Tester`s username'),
        ),
        migrations.AlterField(
            model_name='speedtestresult',
            name='duration',
            field=models.DurationField(help_text='Time between current timestamp and timestamp of test beginning', verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='speedtestresult',
            name='result_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Result ID'),
        ),
        migrations.AlterField(
            model_name='speedtestresult',
            name='speed',
            field=models.FloatField(help_text='Speed of connection for current test unit in mbit/sec', verbose_name='Speed'),
        ),
        migrations.AlterField(
            model_name='speedtestresult',
            name='unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='connection_speed_measurement.SpeedTestUnit', verbose_name='Unit ID'),
        ),
        migrations.AlterField(
            model_name='speedtestunit',
            name='begin_timestamp',
            field=models.DateTimeField(help_text='Timestamp of test beginning', verbose_name='Begin'),
        ),
        migrations.AlterField(
            model_name='speedtestunit',
            name='packet_count',
            field=models.IntegerField(help_text='Number of packets in test', verbose_name='Packet count'),
        ),
        migrations.AlterField(
            model_name='speedtestunit',
            name='packet_number',
            field=models.IntegerField(help_text='Order number of packet in test', verbose_name='Packet number'),
        ),
        migrations.AlterField(
            model_name='speedtestunit',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='connection_speed_measurement.SpeedTest', verbose_name='Test ID'),
        ),
        migrations.AlterField(
            model_name='speedtestunit',
            name='unit_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Unit ID'),
        ),
    ]
