# Generated by Django 3.0.5 on 2020-05-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_speed_measurement', '0003_auto_20200503_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedtest',
            name='file',
            field=models.TextField(help_text='Binary data for speed testing', verbose_name='File data'),
        ),
    ]
