# Generated by Django 3.0.5 on 2020-06-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_speed_measurement', '0003_auto_20200510_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='speedtestunit',
            name='mode',
            field=models.CharField(blank=True, choices=[('download', 'download'), ('upload', 'upload')], default='download', max_length=15, verbose_name='Method choice'),
        ),
        migrations.AlterField(
            model_name='speedtestresult',
            name='duration',
            field=models.FloatField(blank=True, help_text='Time between current timestamp and timestamp of test beginning', null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='speedtestresult',
            name='speed',
            field=models.FloatField(blank=True, help_text='Speed of connection for current test unit in mbit/sec', null=True, verbose_name='Speed'),
        ),
        migrations.AlterField(
            model_name='speedtesttotalresult',
            name='download_speed',
            field=models.FloatField(help_text='Download average speed in mbit/sec', verbose_name='Download average speed'),
        ),
        migrations.AlterField(
            model_name='speedtesttotalresult',
            name='upload_speed',
            field=models.FloatField(help_text='Upload average speed in mbit/sec', verbose_name='Upload average speed'),
        ),
        migrations.AlterField(
            model_name='speedtestunit',
            name='begin_timestamp',
            field=models.DateTimeField(blank=True, help_text='Timestamp of test beginning', verbose_name='Begin'),
        ),
    ]
