# Generated by Django 3.0.5 on 2020-05-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_speed_measurement', '0004_auto_20200505_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedtest',
            name='file',
            field=models.TextField(blank=True, help_text='Data for speed testing', verbose_name='File data'),
        ),
    ]
