# Generated by Django 3.0.5 on 2020-05-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_speed_measurement', '0005_auto_20200507_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedtest',
            name='file_size_mb',
            field=models.IntegerField(help_text='Size of data for speed testing in megabytes', verbose_name='File size'),
        ),
    ]
