# Generated by Django 3.0.5 on 2020-05-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_speed_measurement', '0009_auto_20200512_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedtestresult',
            name='duration',
            field=models.DurationField(blank=True, help_text='Time between current timestamp and timestamp of test beginning', verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='speedtestresult',
            name='speed',
            field=models.FloatField(blank=True, help_text='Speed of connection for current test unit in mbit/sec', verbose_name='Speed'),
        ),
        migrations.AlterField(
            model_name='speedtestunit',
            name='mode',
            field=models.CharField(blank=True, choices=[('download', 'download'), ('upload', 'upload')], default='download', max_length=15, verbose_name='Method choice'),
        ),
    ]
