# Generated by Django 3.0.5 on 2020-05-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_speed_measurement', '0010_auto_20200513_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedtestresult',
            name='duration',
            field=models.DurationField(blank=True, help_text='Time between current timestamp and timestamp of test beginning', null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='speedtestresult',
            name='speed',
            field=models.FloatField(blank=True, help_text='Speed of connection for current test unit in mbit/sec', null=True, verbose_name='Speed'),
        ),
    ]
