# Generated by Django 3.0.5 on 2020-05-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_speed_measurement', '0011_auto_20200513_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedtestresult',
            name='duration',
            field=models.FloatField(blank=True, help_text='Time between current timestamp and timestamp of test beginning', null=True, verbose_name='Duration'),
        ),
    ]
