# Generated by Django 3.0.5 on 2020-05-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_speed_measurement', '0012_auto_20200516_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedtestunit',
            name='begin_timestamp',
            field=models.DateTimeField(blank=True, help_text='Timestamp of test beginning', verbose_name='Begin'),
        ),
    ]
