nginx: 
  http_port: 80
  server_ip: "{{ hostvars[inventory_hostname]['ansible_env'].SSH_CONNECTION.split(' ')[2] }}"
  wsgi_server_port: 8000

app:
  deploy_user: valentain_sav_99_gmail_com
  app_name: django_backend_practice_2020
  repo_dir: "/home/valentain_sav99_gmail_com/practice2020"
  app_dir: "/home/valentain_sav99_gmail_com/practice2020/django_backend_practice_2020"
  code_repository_url: https://github.com/team-number-15/practice-2020
  venv_dir: "/home/valentain_sav99_gmail_com/envs/django_backend_practice_2020"
  venv_python: "/home/valentain_sav99_gmail_com/envs/django_backend_practice_2020/bin/python3.6"

wsgi:
  django_wsgi_module: config.wsgi
  django_settings_module: config.settings.production
  django_secret_key: 'OLATBchnPKO7Fkb[[;*]?iU]N~qP2MF3W-!)-I:A$OX3c,Yte1'
  #database_url: "{{db.db_url}}" #postgresql://{{app.deploy_user}}:{{db_password}}@{{ hostvars[postgres-server].ansible_host }}/{{app.app_name}}
  deploy_dir: '/home/valentain_sav_99_gmail_com/practice2020/django_backend_practice_2020/deploy'

db:
  #db_url: postgresql://{{deploy_user}}:{{db_password}}@{{ hostvars[postgres-server].ansible_host }}/{{app.app_name}}\
  db_url: postgresql://valentain_sav_99_gmail_com:DfkbrGbljhfc123@35.242.231.40/django_backend_practice_2020
  db_name: "{{ app.app_name }}"
  db_user: "{{app.deploy_user}}"




