- name: Install nginx
  yum: 
    name: nginx 
    state: latest
  become: yes
  

- name: Create nginx config file
  template: 
    src: nginx_conf_template.conf
    dest: "/etc/nginx/conf.d/{{ app.app_name }}.conf"
  become: yes
  notify:
    - restart nginx


