# - name: install required soft
#   import_tasks: install_soft.yml
#   tags: 
#     - django_deploy

- name: get django app
  import_tasks: prepare_django.yml
  tags: 
    - django_deploy

- name: config nginx
  import_tasks: config_nginx.yml
  tags: 
    - django_deploy

- name: config gunicorn
  import_tasks: config_gunicorn.yml
  tags: 
    - django_deploy

- name: systemd for gunicorn_start.sh
  import_tasks: gunicorn_daemon.yml