# - name: Create a new database with name 'speed-tests'
#   mysql_db:
#     name: speed-tests
#     state: present

##
# Set up and configure postgres
##
- name: Create database
  postgresql_db: 
    name: "{{ app.app_name }}"
    state: present
  become_user: postgres
  become: yes